### ISSUE TITLE
Release to CRAN

### ISSUE THREAD

**Issue by russellpierce** [kirillseva/ruigi#6]
Are there any major barriers to releasing to CRAN at this point?

**Comment by kirillseva** [comment]
@drknexus sorry for the supertimely reply! :D I guess now that we're approaching the one year anniversary I do owe you an answer.
I personally use [lockbox](https://github.com/robertzk/lockbox) and [syberia](http://syberia.io) to manage my dependencies, which I actually prefer to pull from github.

If you want this library released to CRAN - get some +1s on this issue and I'll get right to it! And do open new issues with feature requests if you find this library useful and would love to see more features, that would help me get my OSS mojo back. I've been thinking of integrating a cloud backend to schedule remote jobs, but it'll be a considerable undertaking that I don't feel like doing unless someone is willing to use it and give me feedback :)

**Comment by russellpierce** [comment]
Thanks for pointing out lockbox, I've been looking for something like that! For my part my needs got more complex, so I moved on to Apache Airflow for now. All the same, thanks for open sourcing this package.
